apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o kubernetes/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-broker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o kubernetes/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt-broker
    spec:
      containers:
        - args:
            - /usr/sbin/mosquitto
            - -c
            - /mosquitto-no-auth.conf
          image: eclipse-mosquitto:2.0.18
          name: mqtt-broker
          ports:
            - containerPort: 1883
          resources: {}
      hostname: mqtt-broker
      restartPolicy: Always
status: {}
